function datos = importFromMongoDB(obj)
            % Method to import "Operation Points" data from a MongoDB
            % database. "Operation point" data type is of the kind
            % generated by this class method generateOpPtObj
            %
            % Use:
            % datos = importFromDatabase()
            % 
            % This method takes no inputs and outputs the requested data.
            % The connection to the database is configured trough the
            % class properties server, port, dbname and collection
            
            obj.importLibraries;
            
            % Establish connection to database using JAVA library and
            % publish new entry
%             logger = org.apache.log4j.Logger.getLogger("com.mongodb.MongoClient");
%             org.apache.log4j.BasicConfigurator.configure();
%             logger.setLevel(org.apache.log4j.Level.INFO);
            
            if isempty(obj.user)
                mongoClient = com.mongodb.client.MongoClients.create(...
                    sprintf("mongodb://%s:%s", obj.server, obj.port));
            else
                mongoClient = com.mongodb.client.MongoClients.create(...
                    sprintf("mongodb+srv://%s:%s@medpsa.myhxe.mongodb.net/?authSource=admin&replicaSet=atlas-qx88my-shard-0&readPreference=primary&ssl=true", ...
                    obj.user, obj.password));
            end
            
            db =  mongoClient.getDatabase(obj.dbname);
            col = db.getCollection(obj.collection);
            
            cursor = col.find().iterator();
            i=1;
            try 
                while (cursor.hasNext()) 
                    data_json = string( cursor.next().toJson() );
                    data = jsondecode(data_json);
                    data.time = datetime(...
                        data.time.x_date, ...
                        InputFormat = "uuuu-MM-dd'T'HH:mm:ss.SSS'Z'", ...
                        Timezone = "UTC" );
                    
                    % Eliminar campo x_id introducido por db ATLAS creo
                    if sum(strcmp(fieldnames(data), 'x_id')) == 1
                        data = rmfield(data,"x_id"); 
                    end
                    
                    datos(i) = data;
                    i=i+1;
                end
            catch MException
                cursor.close();
                disp(MException)
            end
            
            datos = table2timetable( struct2table(datos) );
        end
